import assert from 'node:assert/strict';
import * as THREE from 'three';
import { createHarness } from './harness.mjs';
const api = createHarness(); api.init();
const bot = api.G.bots.find(b => b.type === 'zombie');
const direction = new THREE.Vector3(1,0,0);
api.knockMob(bot, direction);
assert(!bot.airborne, 'A live uncaptured mob cannot be launched');
const origin = bot.mesh.position.clone();
api.weaponEffect(origin, origin.clone().addScaledVector(direction, 2), 'grenade');
api.updateGrenades(.1);
assert(!bot.airborne, 'Grenade passing an uncaptured mob only produces feedback');
bot.pendingCapture = true;
api.G.resolutions.push({bot, bet:1, loot:{type:'med',label:'醫療包',odds:5},life:0,weapon:'grenade',direction});
api.settleCaptures(0);
assert(bot.dead && bot.airborne > 0, 'Successful grenade capture launches the mob');
api.updateGrenades(.1);
assert(bot.mesh.position.y > 0, 'Captured body follows an airborne arc');
const boss = {dead:true,type:'boss'};
api.knockMob(boss,direction);
assert(!boss.airborne,'Boss cannot be launched');
