import assert from 'node:assert/strict';
import * as THREE from 'three';
import { createHarness } from './harness.mjs';

const api = createHarness();
api.init();
const player = api.G.player;
const dir = new THREE.Vector3(0, 0, -1);
const credits = api.G.credits;
api.G.auto = false;
api.G.hoverTarget = null;
api.G.fireCd = 0;
api.shoot(player, dir, true);
assert.equal(api.G.credits, credits, 'Blank space never charges a shot');
assert.equal(api.G.tracers.length, 0);
const target = api.G.bots.find(b => !b.dead);
api.G.hoverTarget = target;
api.shoot(player, dir, true);
assert.equal(api.G.credits, credits - api.G.bet, 'A selected live mob enables fire');
api.G.fireCd = 0;
target.pendingCapture = true;
api.shoot(player, dir, true);
assert.equal(api.G.credits, credits - api.G.bet, 'Pending capture cannot be fired on');
target.pendingCapture = false;
target.dead = true;
api.shoot(player, dir, true);
assert.equal(api.G.credits, credits - api.G.bet, 'Captured targets cannot be fired on');
api.G.auto = true;
api.G.autoTarget = null;
api.shoot(player, dir, true);
assert.equal(api.G.credits, credits - api.G.bet, 'AUTO also requires a live target');
